name: QMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      run: sudo apt update && sudo apt install -yq qt5-qmake qt5-default qttools5-dev-tools
    
    - name: Configure
      run: qmake
    
    - name: Make
      run: make
    
